In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("data\\npf_train.csv")
df

,id,date,class4,partlybad,CO2168.mean,CO2168.std,CO2336.mean,CO2336.std,CO242.mean,CO242.std,...,T672.mean,T672.std,T84.mean,T84.std,UV_A.mean,UV_A.std,UV_B.mean,UV_B.std,CS.mean,CS.std
0,1,2000-01-17,Ib,False,368.771711,0.310309,368.665658,0.305127,369.371184,0.333606,...,-1.476016,0.250952,-0.899393,0.271648,2.492491,1.310880,0.031587,0.018122,0.000243,0.000035
1,2,2000-02-28,nonevent,False,378.197295,1.001493,378.083089,1.025472,378.671311,1.017208,...,1.479493,0.313460,2.033191,0.271090,0.295937,0.177836,0.005140,0.003552,0.003658,0.000940
2,3,2000-03-24,Ib,False,373.043158,0.749865,372.930066,0.728411,373.569735,0.835240,...,-0.270844,2.037111,0.780422,2.334741,14.434789,8.627312,0.353743,0.272472,0.000591,0.000191
3,4,2000-03-30,II,False,375.643019,0.558629,375.549430,0.540964,376.045849,0.580730,...,5.622308,2.509758,6.533544,2.695277,16.077513,9.984686,0.568242,0.451830,0.002493,0.000466
4,5,2000-04-04,nonevent,False,377.661030,0.408421,377.609576,0.423963,378.117134,0.417243,...,1.140121,1.438071,2.133774,1.614122,9.710422,7.054069,0.339135,0.291457,0.004715,0.000679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,460,2011-08-16,nonevent,False,381.016623,4.411571,381.030844,4.062115,382.901742,5.061991,...,16.319361,1.089563,17.268471,1.308728,8.688739,8.320799,0.464422,0.496816,0.002423,0.000425
460,461,2011-08-19,nonevent,False,383.698146,8.418351,384.052632,8.130389,386.436800,9.901536,...,15.820245,2.868514,16.352391,3.055122,18.475262,12.838481,0.884404,0.726461,0.002476,0.000902
461,462,2011-08-21,nonevent,False,379.279128,12.045785,379.363087,11.533353,381.268591,14.043508,...,14.421092,1.696894,15.094141,1.745526,8.099394,5.851942,0.416961,0.363890,0.003484,0.000457
462,463,2011-08-22,nonevent,False,384.443758,6.413297,384.364392,5.781036,386.384762,7.663215,...,15.049728,0.969001,16.076217,1.197644,11.665070,10.062797,0.622831,0.595032,0.004782,0.001082
463,464,2011-08-27,nonevent,False,382.230839,6.407469,382.448601,6.242533,384.061748,7.748701,...,21.040539,2.466867,21.946135,2.604069,16.670267,11.216294,0.899029,0.722553,0.006956,0.000605

Preprocessing

In [12]:
Data = df.drop(['id','date','partlybad'], axis=1)
Data['class4'].replace(['nonevent', 'Ia', 'Ib', 'II'],[0, 1, 2, 3], inplace=True)
Data["class2"] = (Data["class4"]!= 0).astype(int)
Data

,class4,CO2168.mean,CO2168.std,CO2336.mean,CO2336.std,CO242.mean,CO242.std,CO2504.mean,CO2504.std,Glob.mean,...,T672.std,T84.mean,T84.std,UV_A.mean,UV_A.std,UV_B.mean,UV_B.std,CS.mean,CS.std,class2
0,2,368.771711,0.310309,368.665658,0.305127,369.371184,0.333606,368.616053,0.302364,41.650106,...,0.250952,-0.899393,0.271648,2.492491,1.310880,0.031587,0.018122,0.000243,0.000035,1
1,0,378.197295,1.001493,378.083089,1.025472,378.671311,1.017208,378.029508,1.022258,3.478842,...,0.313460,2.033191,0.271090,0.295937,0.177836,0.005140,0.003552,0.003658,0.000940,0
2,2,373.043158,0.749865,372.930066,0.728411,373.569735,0.835240,372.869868,0.692828,297.954063,...,2.037111,0.780422,2.334741,14.434789,8.627312,0.353743,0.272472,0.000591,0.000191,1
3,3,375.643019,0.558629,375.549430,0.540964,376.045849,0.580730,375.506013,0.529970,324.318386,...,2.509758,6.533544,2.695277,16.077513,9.984686,0.568242,0.451830,0.002493,0.000466,1
4,0,377.661030,0.408421,377.609576,0.423963,378.117134,0.417243,377.582242,0.424460,167.479964,...,1.438071,2.133774,1.614122,9.710422,7.054069,0.339135,0.291457,0.004715,0.000679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,0,381.016623,4.411571,381.030844,4.062115,382.901742,5.061991,381.072078,3.840630,121.227780,...,1.089563,17.268471,1.308728,8.688739,8.320799,0.464422,0.496816,0.002423,0.000425,0
460,0,383.698146,8.418351,384.052632,8.130389,386.436800,9.901536,384.105592,7.952936,332.744478,...,2.868514,16.352391,3.055122,18.475262,12.838481,0.884404,0.726461,0.002476,0.000902,0
461,0,379.279128,12.045785,379.363087,11.533353,381.268591,14.043508,379.163200,10.932955,114.298822,...,1.696894,15.094141,1.745526,8.099394,5.851942,0.416961,0.363890,0.003484,0.000457,0
462,0,384.443758,6.413297,384.364392,5.781036,386.384762,7.663215,384.186892,5.506259,180.454576,...,0.969001,16.076217,1.197644,11.665070,10.062797,0.622831,0.595032,0.004782,0.001082,0
463,0,382.230839,6.407469,382.448601,6.242533,384.061748,7.748701,382.502587,6.174042,297.137573,...,2.466867,21.946135,2.604069,16.670267,11.216294,0.899029,0.722553,0.006956,0.000605,0

EDA

In [15]:
# Class2 correlation
class2_df = Data.drop(['class4'], axis=1)
class_2_corr_matrix = class2_df.corr()
class_2_corr_matrix

,CO2168.mean,CO2168.std,CO2336.mean,CO2336.std,CO242.mean,CO242.std,CO2504.mean,CO2504.std,Glob.mean,Glob.std,...,T672.std,T84.mean,T84.std,UV_A.mean,UV_A.std,UV_B.mean,UV_B.std,CS.mean,CS.std,class2
CO2168.mean,1.000000,-0.375683,0.999689,-0.357720,0.993923,-0.386361,0.998887,-0.361196,-0.490670,-0.529465,...,-0.355898,-0.616646,-0.378436,-0.510366,-0.534933,-0.517513,-0.529989,-0.075707,-0.094106,-0.306268
CO2168.std,-0.375683,1.000000,-0.382443,0.989459,-0.314103,0.950501,-0.393035,0.983460,0.323637,0.431715,...,0.309532,0.689647,0.331910,0.399692,0.468718,0.509401,0.541731,0.401461,0.313584,-0.095968
CO2336.mean,0.999689,-0.382443,1.000000,-0.363388,0.992857,-0.393179,0.999642,-0.365621,-0.486944,-0.526475,...,-0.353411,-0.615212,-0.376512,-0.506721,-0.532078,-0.514251,-0.527439,-0.078667,-0.097018,-0.302710
CO2336.std,-0.357720,0.989459,-0.363388,1.000000,-0.297806,0.933981,-0.372792,0.989742,0.319925,0.423413,...,0.313550,0.678480,0.329417,0.393867,0.459423,0.504802,0.534597,0.414762,0.323141,-0.108067
CO242.mean,0.993923,-0.314103,0.992857,-0.297806,1.000000,-0.305288,0.991031,-0.302495,-0.477680,-0.509829,...,-0.347932,-0.577646,-0.365269,-0.491198,-0.511838,-0.488047,-0.498961,-0.051558,-0.081027,-0.329859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UV_B.mean,-0.517513,0.509401,-0.514251,0.504802,-0.488047,0.541506,-0.513254,0.507805,0.922254,0.944413,...,0.737309,0.768640,0.773786,0.956206,0.963302,1.000000,0.990175,0.226156,0.201294,0.398133
UV_B.std,-0.529989,0.541731,-0.527439,0.534597,-0.498961,0.571422,-0.526699,0.539947,0.892622,0.945305,...,0.713120,0.794205,0.746877,0.935608,0.968980,0.990175,1.000000,0.253799,0.232732,0.349509
CS.mean,-0.075707,0.401461,-0.078667,0.414762,-0.051558,0.360205,-0.083602,0.412537,0.141024,0.180828,...,0.238856,0.403404,0.244597,0.169788,0.208371,0.226156,0.253799,1.000000,0.640050,-0.280109
CS.std,-0.094106,0.313584,-0.097018,0.323141,-0.081027,0.272953,-0.101497,0.329124,0.145934,0.195276,...,0.210057,0.349611,0.226658,0.171914,0.216255,0.201294,0.232732,0.640050,1.000000,-0.052540
class2,-0.306268,-0.095968,-0.302710,-0.108067,-0.329859,-0.087938,-0.298870,-0.113931,0.569286,0.482361,...,0.491762,0.097916,0.520809,0.515946,0.442148,0.398133,0.349509,-0.280109,-0.052540,1.000000

In [53]:
#class2_df.replace('')

#replace()

#class_2_corr_matrix['class2']

columns = class2_df.columns
corr_list = class_2_corr_matrix['class2']
pairs = []

for i in range(0,100):
    pairs.append([columns[i],corr_list[i]])

corr_data = pd.DataFrame(pairs, columns = ['var','corr']).sort_values(by = ['corr'])



#seen = []

for row in corr_data.iterrows():
    
    
    print(row[1][0],row[1][1])

RHIRGA42.mean -0.6303037728117221
RHIRGA84.mean -0.6302353515668089
RHIRGA168.mean -0.6272487640582094
RHIRGA336.mean -0.6233436027313253
RHIRGA504.mean -0.62093390040523
RHIRGA672.mean -0.616959671851979
CO242.mean -0.3298591683640428
CO2168.mean -0.3062677725849482
CO2336.mean -0.3027104463857694
CO2504.mean -0.29887002611136815
H2O672.mean -0.28529104910253555
NOx672.mean -0.2843708352961923
H2O504.mean -0.28349790384778184
NOx504.mean -0.282649016085796
H2O336.mean -0.2814483541666748
CS.mean -0.2801088371775242
NOx336.mean -0.27903931590177283
H2O168.mean -0.2779004960974741
NOx42.mean -0.2763319493539372
NOx168.mean -0.2746666244556174
H2O84.mean -0.27456742729778116
H2O42.mean -0.27131752738172227
NOx84.mean -0.27065622937352296
SWS.std -0.26767867359653347
PTG.mean -0.2013363764325219
NO42.mean -0.15285334730713054
NO672.mean -0.15283971348117248
NO504.mean -0.1427283553385393
NO336.mean -0.13899493555834266
NOx672.std -0.13807491764210664
NOx336.std -0.1328652795952393
NO84.mean -0.12969447935908074
NO168.mean -0.12711786570958505
CO2504.std -0.11393071175338405
CO2336.std -0.10806722126177942
NO672.std -0.10621825265675536
SO2168.mean -0.10607274204423878
NOx42.std -0.10229014300609289
NOx504.std -0.10067517784623521
CO2168.std -0.09596773222529283
NOx84.std -0.08856140177141122
CO242.std -0.08793756522917202
NOx168.std -0.08621634324168662
NO504.std -0.07816736764207194
NO84.std -0.07182796919968032
NO336.std -0.0684784402073021
CS.std -0.052540493044294825
NO42.std -0.048937908784826976
NO168.std -0.02889094144584606
SO2168.std 0.021836850205243796
H2O42.std 0.0429912661787481
H2O84.std 0.043492421368328156
H2O672.std 0.04823407161639544
H2O336.std 0.053599475458199625
H2O168.std 0.05382781936053976
H2O504.std 0.05559773476898482
O3672.std 0.0583350961536242
O3504.std 0.06857651178243922
T672.mean 0.09038205226004244
T504.mean 0.09221095083134237
T42.mean 0.09537136862991118
T168.mean 0.0969533803420526
T84.mean 0.09791564973889198
O3168.std 0.10349253494567821
O384.std 0.11090869350078807
O342.std 0.11189109242813612
Pamb0.std 0.15887982366599784
Pamb0.mean 0.1628416285793566
RPAR.std 0.31087959454553155
SWS.mean 0.33076218983099454
UV_B.std 0.34950884356503487
RPAR.mean 0.3512351054995386
UV_B.mean 0.39813282883963186
PTG.std 0.4003004861482156
UV_A.std 0.44214768665467824
O3672.mean 0.4584635742752814
O3504.mean 0.46028886023006693
O342.mean 0.46498197719759893
O3168.mean 0.4650462351228472
PAR.std 0.46556287408440616
O384.mean 0.4659961516105284
RGlob.std 0.4770142978023538
Glob.std 0.4823613872170203
NET.mean 0.4860950497781952
T672.std 0.4917617104790725
RHIRGA672.std 0.4923969684862171
NET.std 0.4941777342209414
T504.std 0.5004737823457942
RHIRGA504.std 0.512714663105383
T168.std 0.5137207156670877
UV_A.mean 0.5159460057980406
T42.std 0.5200633338364731
T84.std 0.5208087762952726
RHIRGA336.std 0.5215703586992088
RHIRGA168.std 0.5319634825419046
RHIRGA84.std 0.5349069768415518
RHIRGA42.std 0.5403264584142776
PAR.mean 0.5494251141422619
RGlob.mean 0.5597349234966705
Glob.mean 0.5692861543776345